# Generated by Django 5.2.1 on 2025-06-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.AutoField(help_text='Identificacao do Instrutor', primary_key=True, serialize=False)),
                ('rg', models.CharField(help_text='Informe o RG do Instrutor', max_length=15)),
                ('nome', models.CharField(help_text='Informe o nome do Instrutor', max_length=70)),
                ('dataNascimento', models.DateField(help_text='Informe a data de Nascimento')),
                ('telefone', models.CharField(help_text='Informe o número de telefone', max_length=9)),
                ('ddd', models.CharField(help_text='Informe o DDD', max_length=3)),
            ],
        ),
    ]
