# Generated by Django 5.2.1 on 2025-06-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiposdeatividade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposDeAtividade',
            fields=[
                ('codigo', models.AutoField(help_text='Código do Tipo de Atividade', primary_key=True, serialize=False)),
                ('descricao', models.CharField(help_text='Informe a descrição do Tipo de Atividade', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='TipoDeAtividade',
        ),
    ]
