# Generated by Django 5.2.1 on 2025-06-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.AutoField(help_text='Digite o numero de Matrícula', primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Digite o Nome do Aluno', max_length=60)),
                ('dataInicial', models.DateField(help_text='Informe a Data Inicial')),
                ('dataFinal', models.DateField(help_text='Informe a Data Final')),
            ],
        ),
    ]
