# Generated by Django 5.2.1 on 2025-06-06 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_alter_aluno_datafinal_alter_aluno_datainicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='dataFinal',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 6, 23, 56, 29, 377723, tzinfo=datetime.timezone.utc), help_text='Informe a Data Final', null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dataInicial',
            field=models.DateField(default=datetime.datetime(2025, 6, 6, 23, 56, 29, 377723, tzinfo=datetime.timezone.utc), help_text='Informe a Data Inicial'),
        ),
    ]
