# Generated by Django 5.2.1 on 2025-06-07 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_alter_aluno_datafinal_alter_aluno_datainicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='dataFinal',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 7, 0, 39, 36, 274615, tzinfo=datetime.timezone.utc), help_text='Informe a Data Final', null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dataInicial',
            field=models.DateField(default=datetime.datetime(2025, 6, 7, 0, 39, 36, 274615, tzinfo=datetime.timezone.utc), help_text='Informe a Data Inicial'),
        ),
    ]
