# Generated by Django 5.2.1 on 2025-06-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('codigo', models.AutoField(help_text='Digite o Código', primary_key=True, serialize=False)),
                ('descricao', models.CharField(help_text='Informe a descrição do Titulo', max_length=100)),
            ],
        ),
    ]
