# Generated by Django 5.2.1 on 2025-06-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('numero', models.AutoField(help_text='Número da Turma', primary_key=True, serialize=False)),
                ('horarioAula', models.TimeField(help_text='Horário da Aula')),
                ('duracaoAula', models.SmallIntegerField(help_text='Entre com a duração da Aula')),
                ('dataInicial', models.DateField(help_text='Informe a data inicial da matricula')),
                ('dataFinal', models.DateField(help_text='Informe a data final')),
            ],
        ),
    ]
