# Generated by Django 5.2.1 on 2025-06-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='dataFinal',
            field=models.DateField(help_text='Informe a data final', max_length=10),
        ),
        migrations.AlterField(
            model_name='turma',
            name='dataInicial',
            field=models.DateField(help_text='Informe a data inicial da matricula', max_length=10),
        ),
    ]
