# Generated by Django 5.2.1 on 2025-06-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0002_alter_turma_datafinal_alter_turma_datainicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='dataFinal',
            field=models.DateField(help_text='Informe a data final'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='dataInicial',
            field=models.DateField(help_text='Informe a data inicial da matricula'),
        ),
    ]
