# Generated by Django 5.2.1 on 2025-06-07 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0004_turma_codigo_atividade_turma_id_instrutor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='dataInicial',
            field=models.DateField(default=datetime.datetime(2025, 6, 7, 0, 39, 36, 284711, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial da matricula'),
        ),
    ]
