# Generated by Django 5.2.1 on 2025-06-07 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0005_alter_turma_datainicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='dataInicial',
            field=models.DateField(default=datetime.datetime(2025, 6, 7, 0, 44, 2, 97104, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial da matricula'),
        ),
    ]
